# Generated by Django 4.1.3 on 2022-12-14 17:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techreview', '0002_featured_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featured',
            name='article_text',
            field=models.TextField(max_length=1500, validators=[django.core.validators.MinLengthValidator(50)]),
        ),
        migrations.AlterField(
            model_name='featured',
            name='category',
            field=models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(2)]),
        ),
        migrations.AlterField(
            model_name='featured',
            name='summary',
            field=models.TextField(max_length=50, validators=[django.core.validators.MinLengthValidator(10)]),
        ),
        migrations.AlterField(
            model_name='featured',
            name='title',
            field=models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(5)]),
        ),
    ]
