# Generated by Django 4.1.3 on 2022-11-29 20:29

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='photo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='short_introduction',
            field=models.TextField(blank=True, max_length=80, null=True),
        ),
    ]
