# Generated by Django 4.1.3 on 2022-12-14 17:51

import django.core.validators
from django.db import migrations, models
import web_project.core.parameters_validators


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, null=True, validators=[django.core.validators.MinLengthValidator(2), web_project.core.parameters_validators.validate_is_letters]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_name',
            field=models.CharField(blank=True, max_length=30, null=True, validators=[django.core.validators.MinLengthValidator(2), web_project.core.parameters_validators.validate_is_letters]),
        ),
    ]
