# Generated by Django 4.1.3 on 2022-11-30 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=20)),
                ('event_date', models.DateTimeField()),
                ('type_of_event', models.CharField(choices=[('online', 'Online'), ('presence', 'Presence')], max_length=8)),
                ('capacity', models.PositiveIntegerField()),
                ('price', models.PositiveIntegerField(blank=True, null=True)),
                ('country', models.CharField(blank=True, max_length=56, null=True)),
                ('city', models.CharField(blank=True, max_length=85, null=True)),
            ],
        ),
    ]
