# Generated by Django 4.1.3 on 2022-12-10 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='price',
        ),
        migrations.AddField(
            model_name='event',
            name='starting_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
