# Generated by Django 4.1.3 on 2022-12-04 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='description',
            field=models.TextField(default='.', max_length=150),
            preserve_default=False,
        ),
    ]
