# Generated by Django 4.1.3 on 2022-11-30 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_photo_event_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='photo',
        ),
    ]
