# Generated by Django 4.1.3 on 2022-12-01 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_event_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='slug',
        ),
    ]
